spring:
  datasource:
    url: jdbc:sqlite:./mobile-parts.db
    driver-class-name: org.sqlite.JDBC
  
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: create
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        globally_quoted_identifiers: false
        hbm2ddl:
          halt_on_error: false
  
  sql:
    init:
      mode: never

  flyway:
    enabled: false
  
  # Disable Spring Cloud Azure compatibility check for local development
  cloud:
    azure:
      compatibility-verifier:
        enabled: false
  
  # Disable ALL Azure autoconfiguration for local development
  autoconfigure:
    exclude:
      - com.azure.spring.cloud.autoconfigure.implementation.context.AzureTokenCredentialAutoConfiguration
      - com.azure.spring.cloud.autoconfigure.implementation.compatibility.AzureCompatibilityVerifierAutoConfiguration
      - com.azure.spring.cloud.autoconfigure.implementation.properties.AzureGlobalPropertiesAutoConfiguration
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

# Disable Firebase for local SQLite development
firebase:
  enabled: false

logging:
  level:
    org.hibernate:
      SQL: DEBUG
      type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.mobileparts: DEBUG
