spring:
  application:
    name: mobile-parts-backend
  
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:supabase}  # Default to supabase profile
  
  datasource:
    url: jdbc:postgresql://localhost:5432/mobileparts
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
  
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    validate-on-migrate: true
  
  # Redis configuration (works locally and on Azure)
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      ssl:
        enabled: ${REDIS_SSL:false}
  
  session:
    store-type: redis
    timeout: 30m
  
  cache:
    type: redis
  
  graphql:
    graphiql:
      enabled: true
      path: /graphiql
    path: /graphql
    schema:
      printer:
        enabled: true
      locations: classpath:graphql/**/*.graphqls
      file-extensions: .graphqls
    cors:
      allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:4200}
      allowed-methods: GET,POST
      allowed-headers: "*"
      allow-credentials: true

# Application Configuration
app:
  security:
    jwt:
      secret: ${JWT_SECRET:your-secret-key-change-in-production-must-be-at-least-256-bits}
      expiration: 86400000 # 24 hours in milliseconds
      refresh-expiration: 604800000 # 7 days
  
  cors:
    allowed-origins:
      - http://localhost:4200
      - https://mobileparts-frontend.azurewebsites.net
  
  rag:
    enabled: true
    offline-mode: ${RAG_OFFLINE_MODE:false}
    offline-model-path: ${RAG_OFFLINE_MODEL_PATH:/models/llama2}
    max-tokens: 2000
    temperature: 0.7
    chunk-size: 1000
    chunk-overlap: 200
  
  payment:
    mock-mode: ${PAYMENT_MOCK_MODE:true}
    provider: ${PAYMENT_PROVIDER:stripe}
    api-key: ${PAYMENT_API_KEY:your-payment-key}
  
  email:
    enabled: true
    mock-mode: ${EMAIL_MOCK_MODE:false}

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
      probes:
        enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

# Logging Configuration
logging:
  level:
    root: INFO
    com.mobileparts: DEBUG
    org.springframework.web: INFO
    org.springframework.security: DEBUG
    org.springframework.graphql: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/mobile-parts-backend.log
    max-size: 10MB
    max-history: 30

# Server Configuration
server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
    include-exception: false
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/graphql
  http2:
    enabled: true
