spring:
  datasource:
    # Supabase PostgreSQL connection
    # Project: uqiawhrnbjtikdxclukn (Ecommerce_db)
    # Database: postgres
    url: jdbc:postgresql://db.uqiawhrnbjtikdxclukn.supabase.co:5432/postgres
    username: postgres
    password: Saketh117
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update  # Use 'update' for development, 'validate' for production
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
  
  sql:
    init:
      mode: never  # Let Flyway handle migrations
  
  # Redis configuration for cart and session management
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      ssl:
        enabled: ${REDIS_SSL:false}
      timeout: 60000
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms
  
  session:
    store-type: redis
    redis:
      namespace: spring:session
      flush-mode: on_save
    timeout: 30m
  
  cache:
    type: redis
    redis:
      time-to-live: 600000  # 10 minutes
  
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    schemas: public
  
  # Disable Spring Cloud Azure for Supabase
  cloud:
    azure:
      compatibility-verifier:
        enabled: false
  
  autoconfigure:
    exclude:
      - com.azure.spring.cloud.autoconfigure.implementation.context.AzureTokenCredentialAutoConfiguration
      - com.azure.spring.cloud.autoconfigure.implementation.compatibility.AzureCompatibilityVerifierAutoConfiguration
      - com.azure.spring.cloud.autoconfigure.implementation.properties.AzureGlobalPropertiesAutoConfiguration

# Firebase configuration (optional for Supabase, using Supabase Auth instead)
firebase:
  enabled: false

# Logging
logging:
  level:
    org.hibernate:
      SQL: DEBUG
      type.descriptor.sql.BasicBinder: TRACE
    org.springframework.web: INFO
    com.mobileparts: DEBUG
