# Azure SQL Server profile configuration
# Usage: Set SPRING_PROFILES_ACTIVE=sqlserver or run with -Dspring.profiles.active=sqlserver
# Required environment variables:
#   AZURE_SQL_SERVER: your-server.database.windows.net
#   AZURE_SQL_DATABASE: your-database-name
#   AZURE_SQL_USERNAME: your-username
#   AZURE_SQL_PASSWORD: your-password

spring:
  cloud:
    azure:
      compatibility-verifier:
        enabled: false
  datasource:
    url: jdbc:sqlserver://${AZURE_SQL_SERVER:mobileparts-server.database.windows.net}:1433;database=${AZURE_SQL_DATABASE:db-mobileparts};encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: ${AZURE_SQL_USERNAME:sql_admin}
    password: ${AZURE_SQL_PASSWORD}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-test-query: SELECT 1

  jpa:
    hibernate:
      ddl-auto: create  # Use 'create' to recreate tables with all new data
    show-sql: true
    defer-datasource-initialization: true  # Allow data.sql to run after schema creation
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: true
        use_sql_comments: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true

  sql:
    init:
      mode: always  # Always run data-sqlserver.sql
      data-locations: classpath:data-sqlserver.sql

  flyway:
    enabled: false  # Disabled for SQL Server, using Hibernate DDL
    validate-on-migrate: true

# Logging for SQL Server troubleshooting
logging:
  level:
    com.microsoft.sqlserver: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
